version: "3.9"

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  front:
    build: ./front
    command: npx serve -s dist -l 8080
    ports:
      - 8080:8080

  office:
    build: ./office
    command: npx serve -s dist -l 8081
    ports:
      - 8081:8081

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - api
      - front
      - office
