version: "3.9"

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8100
    environment:
      - DJANGO_ALLOWED_HOSTS=amanuma-sda.jp,www.amanuma-sda.jp
    ports:
      - 8100:8100
    volumes:
      - ./api:/app

  nginx:
    image: nginx:stable
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./prod/default.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
