version: "3.9"

services:
  api:
    build: ./api
    command: python -m debugpy --listen 0.0.0.0:3000 manage.py runserver 0.0.0.0:8100
    ports:
      - 8100:8100
      - 3000:3000
    volumes:
      - ./api:/app

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:cached
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
