# Start Docker Compose services
docker-up:
	docker-compose -f docker-compose.yaml up -d

# Stop Docker Compose services
docker-down:
	docker-compose -f docker-compose.yaml down

# Start Vite projects
vite-up:
	nohup sh -c "cd front && npm run dev" >/dev/null 2>&1 &
	nohup sh -c "cd office && npm run dev" >/dev/null 2>&1 &

# Run the complete setup
init: docker-up vite-up
