# Generated by Django 4.2 on 2023-08-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='WorshipSchedule',
        ),
    ]
