# Generated by Django 4.2 on 2023-09-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0002_rename_schedule_worshipschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worshipschedule',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
