# Generated by Django 4.2 on 2023-09-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0003_alter_worshipschedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worshipschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
