# Generated by Django 4.2 on 2024-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
